name: URL Routing Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apify_handler.py'
      - 'bot.py'
      - 'test_*.py'
      - '.github/workflows/url-routing-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apify_handler.py'
      - 'bot.py'
      - 'test_*.py'
      - '.github/workflows/url-routing-tests.yml'
  workflow_dispatch:

jobs:
  url-routing-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        # Install only the packages needed for URL routing tests
        pip install python-dotenv

    - name: Create mock config for tests
      run: |
        cat > config.py << EOF
        # Mock config for testing
        apify_api_token = "test_token"
        firecrawl_api_key = "test_token"
        EOF

    - name: Run URL routing tests
      run: |
        python -m pytest test_url_routing_automated.py -v --tb=short

    - name: Run URL detection workflow tests
      run: |
        python -m pytest test_x_scraping.py::TestXScrapingIntegration::test_url_detection_and_id_extraction_workflow -v --tb=short

    - name: Run comprehensive URL routing tests
      run: |
        python -m pytest test_x_scraping.py::TestXScrapingIntegration::test_url_routing_logic_comprehensive -v --tb=short

    - name: Run simple URL routing test
      run: |
        python test_url_routing.py

    - name: Generate test report
      if: always()
      run: |
        echo "## URL Routing Test Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ URL routing logic tests completed" >> $GITHUB_STEP_SUMMARY
        echo "✅ X.com URL detection verified" >> $GITHUB_STEP_SUMMARY
        echo "✅ Tweet ID extraction verified" >> $GITHUB_STEP_SUMMARY
        echo "✅ Routing decision logic verified" >> $GITHUB_STEP_SUMMARY
